### ISSUE TITLE
Reinstate the original links in the README

### ISSUE THREAD

**Issue by mvasilkov** [DeltaZen/super-castle#1]
Hey heyyy

I'm the original author, and I wanted to ask to please not remove the info about me and the js13k compo from the README. I'd also like some kind of attribution on the site where you're publishing my game. That's just a nice thing to do, you know.

Thanks,
Mark V

**Comment by mvasilkov** [comment]
Ping

**Comment by adbenitez** [comment]
hi, so sorry I didn't realize this, it seems when you fork a project the default is not to watch its activity so I didn't receive any notification, 

notice that it is pretty obvious in github that this a fork of your repo, the link to your repo is at the very top under the repo name, that is likely why I removed it from the readme, but I am more than happy to add it also to the readme, will also attribute you in the mini-apps store, it is not like I get anything for putting apps there, nor want I to pretend the apps are mine, users can go to the source code URL from inside the app and see that it is a fork, sorry for not noticing this issue sooner and the discomfort it may have produced :pray:

**Comment by adbenitez** [comment]
I updated the readme, if there is something you would like to tweak, please tell me or even better, feel free to open a PR to adapt to your taste, if you are happy with the current readme then we can close this issue

I also updated the description in the mini-apps store to mention you

**Comment by adbenitez** [comment]
for the store description, you can even create PRs yourself to update the descriptions if you have a Codeberg account, here is my PR updating the description of super castle:
https://codeberg.org/webxdc/xdcget/pulls/149

**Comment by mvasilkov** [comment]
Thank you!
